### ISSUE TITLE
Cannot download Human.db from ensmbl in Docker

### ISSUE THREAD

**Issue by lucavd** [gexijin/idepGolem#490]
Hi, I'm running the docker image on Windows 11 (WSL 2, Ubuntu 22.04 LTS). The installation went fine and also the first start but it crashes when trying to download Human.db from Ensembl. It seems that it is not able to download a file larger than 250-280Mb.
The smaller files were downloaded just fine.
![image](https://github.com/gexijin/idepGolem/assets/7904152/29641331-da66-4c90-b777-2c75b284be62)

I had no limitation on the amount of space for WSL (the available space is stated to be 700GB)

Thank you

**Comment by lucavd** [comment]
maybe is related to this
https://github.com/rstudio/shiny-server/issues/197

**Comment by gexijin** [comment]
Hi Luca,
Thanks for letting us know. 
Have you tried other species with smaller database? 
It could be that it takes too long and RStudio thinks it is not working. 

You can try to download it yourself manually just by pasting that URL shown above in a browser and save the file into the same folder as the iDEP and unzip it.

**Comment by lucavd** [comment]
Hi, I just timed the file... It fails exactly after 300 seconds. I did download the file (flawlessly). I think there is some sort of timeout of the shiny app that times out at 300 seconds.
I am using the docker image/container thus I don't know how to link an external volume to the container in a way it will see that I already have the file

**Comment by lucavd** [comment]
I got it.. it's here https://github.com/gexijin/idepGolem/blob/8b7357fd407416373066f49b0d6a5c48df938d4e/R/fct_database.R#L30

**Comment by lucavd** [comment]
I tried to modify both (putting them at 3000s after cloning the repo but it still goes into timeout

**Comment by gexijin** [comment]
Hi Lucas, I am changing the 300 to 3000 in the master branch. 
Was you able to run the app locally by manual downloading? As long as you put it in the working folder, it should be fine.

**Comment by lucavd** [comment]
Hi Steven, I downloaded the local repo, changed both the timeouts to 3000 but still after 300s the application crashed.

I downloaded the file manually, put it in the data folder (where I previously found the partially downloaded file) but when the app starts, the downloaded file is ignored and the app starts to download a new file, overwriting the one I put in...

Hope this helps

Thank you

**Comment by gexijin** [comment]
There is another place where the download is limited to 300. I changed that as well. It is in the mod_1_load_data.R file. 
```
      file_name <- paste0(db_ver, ".tar.gz")
      options(timeout = 3000)
```
I have changed that. Please pull the most recent version and try again.  I also did some improvement on the UI.

**Comment by lucavd** [comment]
Yeah, I've also tried to modify both, but it still timeout at 300s. I also pulled your last version, which gives me the same problem. I suspect there's some internal setting in {golem} that overwrite the 3000s timeout, but I was unlucky to find it

**Comment by gexijin** [comment]
Hi Lucas, I think I know the problem. 
If you clone the docker image from Docker Hub, then you are using the idepGolem R package installed there. You are not using the source code. Since I forgot to update the docker image, you are still subject to the 300 second time out. 
This morning I realized this is the problem and updated the docker image. Please pull the most recent docker image. This should fix the problem. 
Also, if you are using Docker, then the local database file you downloaded manually has to be visible from inside the docker to be useful.

**Comment by lucavd** [comment]
Hi Steve, you are right. The issue was open because I couldn't download the file using docker, but to modify the package, I installed if as a normal R package, modified the timeout and run the package locally (without docker) but the problem persisted. 
I'm downloading the new docker image and I'll let you know if in that environment it works

From here https://github.com/gexijin/idepGolem/issues/490#issuecomment-1660924770 I was using the package, and not the docker image. Sorry for the misunderstanding

**Comment by gexijin** [comment]
The easiest way is probably to delete the old image and pull it from DockerHub again.

I just tested installing idepGolem as an R package on another laptop, I have no problem. The first time the download progress bar seems stuck and never disappears. I just stopped the Shiny app and restarted it works fine. With this option, if it still times out, you can manually download files into the current folder. Suppose it is c:/users/lucas/My Documents/idep.  Then you want to download http://bioinformatics.sdstate.edu/data/data107/data107.tar.gz      and save to this folder. After unzipping the file, you should see a c:/users/lucas/My Documents/idep/data107   folder, containing two subfolders: db and demo.  The demo subfolder contains some demo files the db folder is empty.
Then download http://bioinformatics.sdstate.edu/data/data107/db/hsapiens_gene_ensembl__Human.db.gz      and unzip it to the db subfolder.   That should work.

**Comment by lucavd** [comment]
Hi Steve, just an update. 
The package works if the human db takes less than 300s to download (I tried a faster connection and it works flawlessly even with the old settings).

It also works if I download the db manually and UNZIP it in the data107/db folder (the unzipping was the passage I was missing before). So, yeee! Thank you!

I just report that the new docker image doesn't work and localhost:3838 points to the shinyserver index.html page

Thank you for your time and work!

**Comment by gexijin** [comment]
Thanks for the report. The docker image needs more work. I forgot how that is prepared. I use a different one on my server. Will fix that.

**Comment by gexijin** [comment]
Hi Lucas, I just updated the Docker image. It turns out that I had two images for iDEP, one for my own server with a different configuration. Another is for local deployment by others. Yesterday I uploaded the wrong one. It should work now. 

My own issue is that I forgot how I made the second image. I only left myself a note on how to update it!

**Comment by gexijin** [comment]
Close it for now.
